#!/bin/sh

if [ "$1" == "export" ]; then
    cd /app && tar --directory=/data -czvf dump.tar.gz . && chmod 777 dump.tar.gz
    exit 0
elif [ "$1" == "import" ]; then
    cd /app
    if [ -f dump.tar.gz ]; then
        tar -xzvf dump.tar.gz --directory /backup && rm -rf /data/* && mv /backup/* /data/
    else
        echo "dump.tar.gz not found"
        exit 1
    fi
else
    echo "Usage: volume_export.sh [export|import]"
    exit 1
fi