#!/bin/sh

if [ "$1" == "export" ]; then
    cd /app && tar --directory=/data -czvf dump.tar.gz . && chmod 777 dump.tar.gz
    exit 0
elif [ "$1" == "import" ]; then
    cd /app
    if [ -f dump.tar.gz ]; then
        tar -xzvf dump.tar.gz --directory /backup && rm -rf /data/* && mv /backup/* /data/
    # else
        echo "dump.tar.gz not found"
        exit 1
    fi
elif [ "$1" == "size" ]; then
    size=$(du -sb /data | awk '{print $1}')
    printf "%s" "$size" > /app/size.txt
    exit 0
elif [ "$1" == "destroy"]; then
    sudo rm -rf /data
    printf "Deleted all contents of persistent volume"
    exit 0
else
    echo "Usage: [export|import|size|destroy]"
    exit 1
fi